services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./:/app

  postgres:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: billingCore
    ports:
      - "5423:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/18/docker

  rabbitmq:
    image: rabbitmq:4.2.5-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: project
      RABBITMQ_DEFAULT_PASS: project
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local